name: "Gera o número da próxima versão (path, minor, major ou snapshot)"

inputs:
  token:
    description: "Token de acesso ao repositório"
    required: true

outputs:
  versao:
    description: "Versão calculada"
    value: ${{ steps.versao.outputs.versao }}

runs:      
  using: "composite"
  steps:
#    - name: Baixando repositório
#      uses: actions/checkout@v4
#    - name: List files in the repository
#      run: |
#        ls ${{ github.workspace }}

    - name: Coleta última versão
      id: ultimatag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
      with:
        fallback: 0.0.0
      env:
        GITHUB_TOKEN: ${{ inputs.token }}

    - name: Número próximas versões
      id: versoes
      uses: "WyriHaximus/github-action-next-semvers@v1"
      with:
        version: ${{ steps.ultimatag.outputs.tag }}

    - name: Versão
      id: versao
      shell: sh
      run: |
        echo "--- Versões ---"
