name: "Criar Vers찾o / Release e Tag"

inputs:
  token:
    description: "Token de acesso ao reposit처rio"
    required: true
  versao:
    description: "Vers찾o calculada"
    required: true


runs:      
  using: "composite"
  steps:
    - name: Baixar artefatos
      uses: actions/download-artifact@v4
      with:
        name: artefatos
        path: artefatos.zip

    - name: Criar Vers찾o / Release e Tag
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      with:
        body: Release ${{ inputs.versao }}
        tag_name: ${{inputs.versao}}
        files: artefatos.zip