name: "Compila o projeto"

inputs:
  node_versao:
    description: Versão do node
    required: true
  node_compilar_pastas:
    type: string
    description: Pastas do projeto node

runs:      
  using: "composite"
  steps:
    - name: Trocando versão do node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node_versao }}

    - name: Cache Node.js modules
      uses: actions/cache@v4
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Compila o(s) projeto(s)
      shell: bash
      run: |
        pastas="${{ inputs.node_compilar_pastas }}"
        pastas=${pastas//;/ } 
        for pasta in $pastas ; do 
          cd ${{ github.workspace }}/build/$pasta ;
          npm ci ;
          npm run build ;
        done
