name: CI - Release
run-name: CI ${{ inputs.versao }} disparada por ${{ github.actor }}

on: 
  workflow_call:
    inputs:
      versao:
        type: string
        description: Vers찾o do artefato
        required: true
      node_compilar_pastas:
        type: string
        description: Pastas do projeto node
      node_artefatos:
        type: string
        description: Arquivos/Artefatos da vers찾o final 

permissions:
  id-token: write
  contents: read

jobs:
  GerarVersao:
    runs-on: ubuntu-latest
    permissions: read-all
    outputs:
      versao: ${{ steps.versao.outputs.versao }}
    steps:
      - name: Checkout Pipeline Files
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/actions_git
          sparse-checkout: .github
          path: scripts

      - name: Coleta a pr처xima vers찾o
        id: versao
        uses: ./scripts/.github/actions/proxima_versao